// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table modules {
  module_id integer [pk]
  module_id_uni varchar
  name varchar [not null]
  org_id varchar [not null, ref: > organisations.org_id]
  level varchar
  lang varchar
  ects integer
  prereq varchar
  description varchar
  valid_from varchar
  valid_to varchar
  link varchar
  link_type varchar
  digital_score int
  name_embedding blob
}

Table topics {
  topic_id integer [pk]
  topic varchar [not null]
  embedding blob
}

Table module_topic_mappings {
  module_id integer [ref: > modules.module_id]
  topic_id integer [ref: > topics.topic_id]
}

Table organisations {
  org_id varchar [pk]
  name varchar [not null]
  org_type varchar
  parent_org_id varchar [ref: > organisations.org_id]
  dep_id varchar [ref: > organisations.org_id]
  school_id varchar [ref: > organisations.org_id]
  link varchar
  homepage varchar
  org_id_tumonline int
  hierarchy int
}

Table module_prerequisites {
  module_prerequisite_id integer [pk]
  module_id_uni integer [not null, ref: > modules.module_id]
  prereq_module_id_uni integer [ref: > modules.module_id]
  prereq_module_title varchar
  is_mandatory boolean
  extraction_method varchar
}

Table prerequisite_mapping {
    module_id_uni varchar [not null]
    prerequisite_module_id_uni varchar [not null]
    module_prerequisite_id [int, ref: > module_prerequisites.module_prerequisite_id]
}

Table other_prerequisites {
  other_prerequisite_id integer [pk]
  module_id_uni integer [ref: > modules.module_id]
  detail_type varchar [not null] // 'knowledge_topic' or 'other_information'
  detail_text varchar [not null]
}