// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table modules {
  module_id integer [pk]
  module_id_uni varchar
  name varchar
  org_id varchar [ref: > organisations.org_id]
  level varchar
  lang varchar
  ects integer
  prereq varchar
  description varchar
  valid_from varchar
  valid_to varchar
  link varchar
  link_type varchar
  digital_score int
}

Table topics {
  topic_id integer [pk]
  topic varchar [not null]
  embedding blob
}

Table module_topic_mappings {
  module_id integer [ref: > modules.module_id]
  topic_id integer [ref: > topics.topic_id]
}

Table organisations {
  org_id varchar [pk]
  name varchar [not null]
  org_type varchar
  parent_org_id varchar [ref: > organisations.org_id]
  link varchar
  homepage varchar
  org_id_tumonline int
  hierarchy int
}